# Generated by Django 5.1.6 on 2025-03-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentprofile',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='conditions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='doctor_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='medication_schedule',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='medications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='reminder_message',
            field=models.TextField(default='Take the medicine'),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
