# Generated by Django 5.1.7 on 2025-03-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_residentprofile_last_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_resident',
            field=models.BooleanField(default=False),
        ),
    ]
