# Generated by Django 5.1.7 on 2025-03-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_customuser_is_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
