# Generated by Django 5.1.7 on 2025-03-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_caregiverprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverprofile',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
