# Generated by Django 5.1.7 on 2025-03-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_caregiverprofile_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
