# Generated by Django 5.1.7 on 2025-03-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_caregiverprofile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caregiverprofile',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caregiverprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='caregiverprofile',
            name='languages',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='caregiverprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='caregiver_pics/'),
        ),
        migrations.AddField(
            model_name='caregiverprofile',
            name='service_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caregiverprofile',
            name='service_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caregiverprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='caregiverprofile',
            name='availability',
            field=models.CharField(choices=[('full-time', 'Full-Time'), ('part-time', 'Part-Time'), ('on-call', 'On-Call')], default='full-time', max_length=20),
        ),
    ]
