# Generated by Django 5.1.7 on 2025-03-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_caregiverprofile_bio_caregiverprofile_certifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiverprofile',
            name='availability',
            field=models.CharField(choices=[('full-time', 'Full-Time'), ('part-time', 'Part-Time'), ('on-call', 'On-Call')], default='full-time', max_length=50),
        ),
    ]
