# Generated by Django 5.1.7 on 2025-03-31 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_customuser_is_visitor_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorprofile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='visitorprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='visitorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile.jpg', upload_to='visitor_profiles/'),
        ),
        migrations.AlterField(
            model_name='visitorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
