# Generated by Django 5.1.7 on 2025-03-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_visitorprofile_full_name_visitorprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visitorprofile',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
