# Generated by Django 5.1.7 on 2025-04-03 13:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_meetingrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingrequest',
            name='requested_date',
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingrequest',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_requests', to='home.residentprofile'),
        ),
        migrations.AlterField(
            model_name='meetingrequest',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_requests', to='home.visitorprofile'),
        ),
    ]
