# Generated by Django 5.1.7 on 2025-04-03 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_meetingrequest_requested_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingrequest',
            old_name='request_date',
            new_name='meeting_datetime',
        ),
        migrations.RemoveField(
            model_name='meetingrequest',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='meetingrequest',
            name='scheduled_time',
        ),
        migrations.AlterField(
            model_name='meetingrequest',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.residentprofile'),
        ),
        migrations.AlterField(
            model_name='meetingrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='meetingrequest',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.visitorprofile'),
        ),
    ]
