# Generated by Django 5.1.7 on 2025-04-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rename_request_date_meetingrequest_meeting_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_resident',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_visitor',
        ),
    ]
