# Generated by Django 5.1.7 on 2025-04-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_customuser_is_resident_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_resident',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_visitor',
            field=models.BooleanField(default=False),
        ),
    ]
