# Generated by Django 5.1.7 on 2025-04-19 16:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_customuser_is_resident_customuser_is_visitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingrequest',
            name='meeting_datetime',
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingrequest',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_requests', to='home.residentprofile'),
        ),
        migrations.AlterField(
            model_name='meetingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='meetingrequest',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_requests', to='home.visitorprofile'),
        ),
    ]
